trigger:
  - main

variables:
  azureSubscription: "ff29e49f-d6f5-4071-bbdd-467139caa4df"

  webAppName: "nodejs-azure-app-service"

  environmentName: "nodejs-azure-app-service"

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      npm install
      npm run build --if-present
      npm run test --if-present
    displayName: "npm install, build and test"

  - task: ArchiveFiles@2
    displayName: "Archive files"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      replaceExistingArchive: true

  - task: AzureWebApp@1
    displayName: "Azure Web App Deploy: nodejs-azure-app-service"
    inputs:
      azureSubscription: $(azureSubscription)
      appType: webAppLinux
      appName: $(webAppName)
      runtimeStack: "NODE|10.10"
      package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
      startUpCommand: "pm2 start dist/index.js --no-daemon"
