name: Continuous Delivery Sync

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: CHECKOUT
        uses: actions/checkout@v3

      - name: SETUP NODE and CACHE
        uses: actions/setup-node@v3
        id: setup-node
        with:
          node-version-file: '.node-version'
          cache: npm

      - name: INSTALL DEPENDENCIES AND BUILD
        run: |
          npm install
          npm run build

      - name: ZIP ARTIFACT
        run: |
          zip -r node-app.zip . -x "*.git*" -x "*.github*" -x "*.husky*" -x ".env"

      - name: UPLOAD ARTIFACT
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: node-app.zip
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 20

    steps:
      - name: DOWNLOAD ARTIFACT
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: UNZIP ARTIFACT
        run: |
          unzip node-app.zip

      - name: DEPLOY TO AZURE
        uses: azure/webapps-deploy@v2
        with:
          app-name: default-a
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }} 
          package: .

      - name: REMOVE ARTIFACT
        run: |
          rm node-app.zip

  sync:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 5

    steps:
      - name: CHECKOUT
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SETUP SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: SETUP GIT
        run: |
          git config --global user.email "augustobritodev@icloud.com"
          git config --global user.name "Augusto Brito"

      - name: PUSH TO REPOSITORY
        run: |
          git remote add sync ${{ secrets.SSH_REPOSITORY }}
          git push sync --force

