name: Continuous Delivery Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: CHECKOUT
        uses: actions/checkout@v3

      - name: SETUP NODE and CACHE
        uses: actions/setup-node@v3
        id: setup-node
        with:
          node-version-file: '.node-version'
          cache: npm

      - name: INSTALL DEPENDENCIES AND BUILD
        run: |
          npm install
          npm run build

      - name: ZIP ARTIFACT
        run: |
          zip -r node-app.zip . -x "*.git*" -x "*.github*" -x "*.husky*" -x ".env"

      - name: UPLOAD ARTIFACT
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: node-app.zip
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 20

    steps:
      - name: DOWNLOAD ARTIFACT
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: UNZIP ARTIFACT
        run: |
          unzip node-app.zip

      - name: DEPLOY TO AZURE
        uses: azure/webapps-deploy@v2
        with:
          app-name: default-a
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }} 
          package: .

      - uses: geekyeggo/delete-artifact@v2
        with:
          name: react-app
